Main Project/hrms/hrms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ultimatix.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main Project/hrms/ultimatix/urls.py
from django.urls import path
from . import views
app_name='ultimatix'

urlpatterns=[
path('home/',views.home_view,name='home_view'),
path('admin/designation/',views.designation_view,name='desig_mngt'),
path('admin/roles/',views.roles_view,name='roles_mngt'),
path('admin/regemp/',views.regemp_view,name='register_emp'),
path('admin/viewemp/',views.viewemp_view,name='view_emp'),
path('admin/viewemp/<int:pk>',views.updtemp_view,name='updt_emp'),
path('admin/createproject/',views.crtprj_view,name='create_project'),
path('admin/viewprojects/',views.proejcts_view,name='view_project'),
path('admin/viewprojects/<int:pid>',views.proejctmembers_view,name='project_members'),
path('admin/viewprojects/updt/<int:pid>',views.updtproj_view,name='updt_project'),
path('admin/allocate/',views.allocate_view,name='emp_allocate'),
#path('admin/deallocate/<int:pmid>',views.deallocate_view,name='emp_deallocate'),
path('ultimatix/attendance/',views.mark_attendance,name="mark_attendance"),
path('ultimatix/attendance/<str:adate>',views.upload_attendance,name="upload_attendance"),
path('ultimatix/applyleave/',views.apply_leave,name="apply_leave"),
path('ultimatix/leaverequest/',views.leave_request,name="leave_request"),
path('ultimatix/calendar/',views.calendar_view,name="calendar_view"),
path('ultimatix/payslip/',views.generate_payslip,name="generate_payslip"),
path('ultimatix/newsfeed/',views.news_feed,name='news_feed'),
path('ultimatix/admin/updttmsheet/',views.updttmsheet,name='updttmsheet'),
path('ultimatix/admin/dashboard/',views.admindashboard,name='admindashboard'),
path('ultimatix/salary/',views.salary_details,name="salary_details"),
path('ultimatix/adminappraisalreq',views.adminappraisalreq,name="adminappraisalreq"),

path('ultimatix/empview_projects',views.empview_projects,name="empview_projects"),
path('ultimatix/empview_projects/<int:pid>',views.empproejctmembers_view,name="empproject_members"),
path('ultimatix/empmyproject/',views.empmyproject,name="empmyproject"),
path('ultimatix/empdetails/',views.empdetails,name='empdetails'),
path('ultimatix/empleave/',views.empleave,name="empleave"),
path('ultimatix/empleavereq/',views.empleavereq,name="empleavereq"),
path('ultimatix/empcalendar/',views.empcalendar,name="empcalendar"),
path('ultimatix/emppayslip/',views.emppayslip,name="emppayslip"),
path('ultimatix/emptsupdt/',views.emptsupdt,name="emptsupdt"),
path('ultimatix/empdtlupdt/',views.empdtlupdt,name="empdtlupdt"),
path('ultimatix/empprofile/',views.empprofile,name="empprofile"),
path('ultimatix/empappraisal/',views.empappraisal,name="empappraisal"),
path('ultimatix/empappraisalreq/',views.empappraisalreq,name="empappraisalreq"),

path('',views.show_login,name="show_login"),


]

Main Project/hrms/ultimatix/views.py
import json
import os

import openpyxl
from django.db import connection,DatabaseError
from django.db.models import Max, Sum
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect

from ultimatix.utils import render_to_pdf
from .models import *
from datetime import datetime
import calendar
#import datetime
from ultimatix import config
import numpy as np
from django.db.models import Q
# Create your views here.
def dictfetchall(cursor):
    """Return all rows from a cursor as a dict"""
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def home_view(request):
    cursor = connection.cursor()
    try:
        logged_in = request.session['eid']
    except:
        logged_in = False

    if logged_in:
        date=datetime.now()
        #date=datetime.strptime('2020-01-01','%Y-%m-%d')
        if (date.day == calendar.monthrange(date.year, date.month)[1]):
            ob=Employee.objects.all().exclude(e_id='1022890')
            ed=str(calendar.monthrange(date.year, date.month)[1])
            yr=str(date.year)
            mn=str(date.month)
            if len(mn)==1:
                mn='0'+mn
            sdate=yr+"-"+mn+"-01"
            #print(sdate+" "+edate)
            sm=yr+"-"+mn
            #em=yr+"-"+str(date.month+1)
            yr2=str(date.year)
            #print('date.month'+str(date.month))
            if date.month==12:
                mn2='01'
                yr2=str(date.year+1)
            else:
                mn2=str(date.month+1)
                if len(mn2)==1:
                    mn2='0'+mn2
            em=yr2+"-"+mn2
            edate = yr + "-" + mn + "-" + ed
            print(sdate+" "+edate)
            print(sm + " "+em)

            busdays=np.busday_count(sm,em)
            print(busdays)

            for o in ob:
                #print(o.e_id)

                sql='''
                select count(*) from ultimatix_timesheet where eid_id=%s and tdate >=%s
                and tdate<=%s and tstate='P'
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                res=cursor.fetchone()
                p=int(res[0])

                sql='''
                select count(*) from ultimatix_timesheet where eid_id=%s and tdate >=%s
                and tdate<=%s and tstate='H'                
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                res=cursor.fetchone()
                h=0.5*int(res[0])

                sql='''
                select count(*) from ultimatix_timesheet where eid_id=%s and tdate >=%s
                and tdate<=%s and tstate='A'                
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                res=cursor.fetchone()
                a=int(res[0])

                sql='''
                select sum(nof) as sum from ultimatix_leave where eid_id=%s and sdate>=%s and edate<=%s
                and status='C'            
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                #cursor.execute(sql)
                res=cursor.fetchone()
                #print(str(res))
                #print(int(res[0]))
                l=0
                if res[0]:
                    #print('record for : '+str(o.e_id))
                    l=int(res[0])
                #if str(o.e_id)=='1022892':
                tot=(p+h)+(a-l)
                print(str(p)+" "+str(h)+" "+str(a)+" "+str(l)+" "+str(tot))
                ctc= float(Employee_sal.objects.get(es_eid_id=o.e_id,es_status='Y').es_ctc)
                ctc_pm=float(ctc/12)
                ctc_pd=float(ctc_pm/int(calendar.monthrange(date.year, date.month)[1]))
                lop=0
                if tot<busdays:
                    lop=(float(busdays)-float(tot))*ctc_pd
                bs = ctc_pm * .40
                conv = ctc_pm * .18
                hra = ctc_pm * .12
                city = ctc_pm * .10
                sundry = ctc_pm * .06
                ptax = ctc_pm * .04
                pf = ctc_pm * .02
                esis = ctc_pm * .08
                r=Wage.objects.filter(eid_id=o.e_id,sdate=sdate,edate=edate,status='Y')
                if not r:
                    Wage.objects.create(eid_id=o.e_id,sdate=sdate,edate=edate,ctc=ctc,ctc_pm=round(ctc_pm,2),
                                        bs=round(float(bs),2),conv=round(float(conv),2),hra=round(float(hra),2),city=round(float(city),2),
                                        sundry=round(float(sundry),2),ptax=round(float(ptax),2),pf=round(float(pf),2),
                                        esis=round(float(esis),2),lop=round(float(lop),2),status='Y')
        elif date.day==1 and date.month in(1,4,7,10):
            ob = Employee.objects.all().exclude(e_id='1022890')
            if date.month == 1:
                for o in ob:
                    o.e_cl=2.0
                    o.e_sl=2.0
                    o.e_el=4.0
                    o.e_fl=2.0
                    o.save()
                    print('flexi and other leave credit')
            else:
                for o in ob:
                    r=Employee.objects.filter(e_id=str(o.e_id),e_cl=2.0,e_sl=2.0)
                    if not r:
                        o.e_cl=2.0
                        o.e_sl=2.0
                        o.e_el=float(o.e_el)+4.0
                        o.save()
                        print('credit other leave')
        else:
            print('not month end')
        news = News.objects.all().order_by('-nid')
        user = Employee.objects.get(e_id=logged_in)
        sql = '''
        select ud.d_role
        from ultimatix_employee ue
        left outer join ultimatix_employee_desig ued on ued.ed_eid_id = ue.e_id
        left outer join ultimatix_designation ud on ud.d_id = ued.ed_did_id
        where ued.ed_status = 'Y' and ue.e_id = %s
        '''
        cursor.execute(sql, [logged_in])
        res = cursor.fetchone()
        if str(res[0])=='0':
            role=0
        elif str(res[0])=='2':
            role=2
        elif str(res[0])=='1':
            role=1
        cursor.close()
        if role==0:
            return render(request, 'ultimatix/admin/adminhome.html',{'user':user,'news':news})
        else:
            return render(request,'ultimatix/employee/emphome.html',{'user':user,'news':news,'role':role})
    else:
        request.session['eid'] = None
        cursor.close()
        return redirect('ultimatix:show_login')





def designation_view(request):
    if request.is_ajax() and request.GET:
        try:
            cd = request.GET.get('cd')
            #print("code : "+cd)
            cursor = connection.cursor()
            sql = """
            select d_cd,d_desc,d_min,d_max,d_role from ultimatix_designation 
        	where d_cd=%s
            """
            cursor.execute(sql,[cd])
            #print("cursor : "+str(cursor))
            dict = dictfetchall(cursor)
            #print(str(dict))
            r = json.dumps(dict[0])
            cursor.close()
            return JsonResponse(r, safe=False)
        except DatabaseError  as e:
            print('Database error : ' + str(e))
        finally:
            if cursor:
                cursor.close()


    elif request.method=='POST':
        # return HttpResponse('submitted')
        cd = request.POST.get("cd")
        desc = request.POST.get("desc")

        if (request.POST.get("minexp").strip()) == '':
            min_exp = None
        else:
            min_exp = int(request.POST.get("minexp"))

        if (request.POST.get("maxexp").strip()) == '':
            max_exp = ''
        else:
            max_exp = int(request.POST.get("maxexp"))

        r_type = request.POST.get("role_select")
        # print('r_type : '+'*'+str(r_type)+'*')
        r_num = -1
        if r_type == "Employee":
            r_num = 1
        elif r_type == "HR":
            r_num = 2
        if request.POST.get("add"):
            ob=Designation.objects.filter(d_cd=cd)
            if ob:
                logged_in = request.session['eid']
                user = Employee.objects.get(e_id=logged_in)
                obj = Designation.objects.all().exclude(d_role=0)
                return render(request, 'ultimatix/admin/designation.html',
                             {'error': ' Designation already exists !','obj':obj,'user':user})
            else:
                try:
                    print('Entered for new save')
                    cursor = connection.cursor()
                    sql="""
                    insert into ultimatix_designation(d_cd,d_desc,d_min,d_max,d_role)
                    values(%s,%s,%s,%s,%s)
                    """
                    cursor.execute(sql, (cd, desc, min_exp, max_exp, r_num))
                    connection.commit()
                    cursor.close()
                    #obj=Designation.objects.create(d_cd=cd,d_desc=desc,d_min=min_exp,d_max=max_exp,d_role=r_num)
                    #obj.save()
                    logged_in = request.session['eid']
                    user = Employee.objects.get(e_id=logged_in)
                    obj = Designation.objects.all().exclude(d_role=0)
                    return render(request, 'ultimatix/admin/designation.html',
                              {'success': ' Data saved successfully!','obj':obj,'user':user})
                except DatabaseError  as e:
                    print('Database error : '+str(e))
                    connection.rollback()
                    obj = Designation.objects.all().exclude(d_role=0)
                    logged_in = request.session['eid']
                    user = Employee.objects.get(e_id=logged_in)
                    return render(request, 'ultimatix/admin/designation.html',
                              {'error': ' Database error.Please contact system admin!','obj':obj,'user':user})

Main Project/hrms/templates/ultimatix/applyleave.html
{% extends 'ultimatix/admin/adminbase.html'%}

{%block body %}
 <style type="text/css">
  .ui-datepicker td.holiday a, .ui-datepicker td.holiday a:hover {
     background: none #f44336;
     border: 1px solid #f44336;
   }
 </style>
<!--  <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/smoothness/jquery-ui.css"/>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>-->
<!--<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.css" />

<h2 class="w3ls_head">Apply for leave</h2>
<div class="grid_3 grid_4 w3layouts">
<!--<h1>{{eid}}</h1>-->
    <div class="bs-example row">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-10">
            <table style="width:100%">
                <tr>
                    <th>Type of Leave</th>
                    <th>Count</th>
                </tr>
                <tr>
                    <td>-----------------------</td>
                    <td>----------</td>
                </tr>
                <tr>
                    <td>Casual leave</td>
                    <td>{{user.e_cl}}</td>
                </tr>
                <tr>
                    <td>Sick leave</td>
                    <td>{{user.e_sl}}</td>
                </tr>
                <tr>
                    <td>Earned leave</td>
                    <td>{{user.e_el}}</td>
                </tr>
                <tr>
                    <td>Flexi leave</td>
                    <td>{{user.e_fl}}</td>
                </tr>
            </table>
                </div>
            </div>
        </div>

        <div class="col-md-4">
        <form action="{% url 'ultimatix:apply_leave'%}" method="post" autocomplete="off">
            {% csrf_token%}
            {% if error %}
            <div class="form-group row">
                <!--<div class="col-md-2"></div>-->
                <div class="col-md-12">
                    <div class="alert alert-danger" id="error">
                        {{error}}
                    </div>
                </div>
                <!--<div class="col-md-2"></div>-->
            </div>
            {% elif success %}
            <div class="form-group row">
                <!--<div class="col-md-2"></div>-->
                <div class="col-md-12">
                    <div class="alert alert-success" id="success">
                        {{success}}
                    </div>
                </div>
                <!--<div class="col-md-2"></div>-->
            </div>
            {%endif%}
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="sdate">Start Date</label>
                    <input type="text" class="form-control ldate" name="sdate" id="sdate" required>
                </div>
                <div class="col-md-6">
                    <label for="edate">End Date</label>
                    <input type="text" class="form-control ldate" name="edate" id="edate" required>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-6">
                    <label for="nof">Number of Days</label>
                    <input type="text" class="form-control" name="nof" id="nof" readonly>
                </div>
                <div class="col-md-6">
                    <label for="leave_select">Leave Type</label>
                    <select  title="Choose Leave Type" class=" form-control" id="leave_select" name="leave_select"required>
						<option value="0">Casual Leave</option>
                        <option value="1">Sick Leave</option>
                        <option value="2">Earned Leave</option>
                        <option value="3">Flexi Leave</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                <div class="checkbox">
                    <label for="chk_half">
                        <input type="checkbox" id="chk_half" name="chk_half">
                        <b>Half Day</b>
                    </label>
                </div>
            </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="rsn">Description</label>
                    <input type="text" class="form-control" name="rsn" id="rsn" required>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-primary form-control" value="submit" name="submit" id="submit">Submit Request</button>
                </div>
                <div class="col-md-3"></div>
            </div>
        </form>

        </div>
        <div class="col-md-4"></div>
    </div>
    {% if lobj %}
    <div class="row">
        <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th style="color:black;">Leave Id</th>
                <th style="color:black;">Date Range</th>
                <!--<th style="color:black;">End Date</th>-->
                <th style="color:black;">Leave Type</th>

                <th style="color:black;">Status</th>
                <th style="color:black;">Pending With</th>
                <th style="color:black;">Description</th>
                <th style="color:black;">Remarks</th>
            </tr>
        </thead>
        <tbody>
            {% for l in lobj %}
            <tr>
                <td style="color:black;">{{l.lid}}</a></td>
                <td style="color:black;">{{l.sdate}} - {{l.edate}} ({{l.nof}}) </td>
                <!--<td style="color:black;">{{l.edate}}</td>-->
                {% if l.ltype == 0 %}
                <td style="color:black;">Casual Leave</td>
                {% elif l.ltype == 1 %}
                <td style="color:black;">Sick Leave</td>
                {% elif l.ltype == 2 %}
                <td style="color:black;">Earned Leave</td>
                {% elif l.ltype == 3 %}
                <td style="color:black;">Flexi Leave</td>
                {%else%}
                <td style="color:black;">Special Leave</td>
                {% endif %}


                <td style="color:black;">{{l.status}}</td>
                <td style="color:black;">{{l.queueid}}</td>
                <td style="color:black;">{{l.desc}}</td>
                {% if l.remarks %}
                <td style="color:black;">{{l.remarks}}</td>
                {% else%}
                <td style="color:black;">-</td>
                {%endif%}
            </tr>
            {%endfor%}

        </tbody>
        <!--<tfoot>
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Office</th>
                <th>Age</th>
                <th>Start date</th>
                <th>Salary</th>
            </tr>
        </tfoot>-->
    </table>
    </div>
    {% endif %}
</div>

<!--<script>
$(document).ready(function(){
	$('#leave').addClass("active");
	$('#leaveapply').addClass("active");

});
</script>-->
<script>
$(document).ready(function(){
    $('#leave').addClass("active");
	$('#leaveapply').addClass("active");

  var holiDays =[
  [2018,01,01,'New Years Day'],[2018,01,14,'Makar Sankranti / Pongal'],[2018,01,26,'Republic Day'],
[2018,02,14,'Maha Shivaratri'],[2018,03,02,'Holi'],[2018,03,18,'Ugadi / Gudi Padwa'],[2018,03,30,'Good Friday'],
[2018,05,01,'Labor Day'],[2018,06,16,'Eid-ul-Fitar'],[2018,08,15,'Independence Day'],[2018,08,22,'Bakri Id / Eid ul-Adha'],
[2018,08,25,'Onam'],[2018,09,13,'Vinayaka Chaturthi'],[2018,09,21,'Muharram'],[2018,10,02,'Mathatma Gandhi Jayanti'],
[2018,10,19,'Dussehra / Dasara'],[2018,11,07,'Diwali / Deepavali'],
[2018,12,25,'Christmas'],

  [2019,01,01,'New Years Day'],[2019,01,14,'Makar Sankranti / Pongal'],
  [2019,01,26,'Republic Day'],[2019,03,04,'Maha Shivaratri'],[2019,03,21,'Holi'],
  [2019,04,06,'Ugadi / Gudi Padwa'],
  [2019,04,19,'Good Friday'],[2019,05,01,'Labor Day'],
  [2019,06,05,'Eid-ul-Fitar'],[2019,08,12,'Bakri Id / Eid ul-Adha'],
  [2019,08,15,'Independence Day'],
  [2019,09,02,'Vinayaka Chaturthi'],[2019,09,10,'Muharram'],[2019,09,11,'Onam'],
  [2019,10,02,'Mathatma Gandhi Jayanti'],[2019,10,08,'Dussehra / Dasara'],
  [2019,10,27,'Diwali / Deepavali'],[2019,12,25,'Christmas']
  ];

$(function() {
  $("#sdate").datepicker({
     beforeShowDay: setHoliDays
  });

  // set holidays function which is configured in beforeShowDay
 function setHoliDays(date) {
   for (i = 0; i < holiDays.length; i++) {
     if (date.getFullYear() == holiDays[i][0]
    	  && date.getMonth() == holiDays[i][1] - 1
          && date.getDate() == holiDays[i][2]) {
        return [true, 'holiday', holiDays[i][3]];
     }
   }
  return [true, ''];
    }

});

$(function() {
  $("#edate").datepicker({
     beforeShowDay: setHoliDays
  });

  // set holidays function which is configured in beforeShowDay
 function setHoliDays(date) {
   for (i = 0; i < holiDays.length; i++) {
     if (date.getFullYear() == holiDays[i][0]
    	  && date.getMonth() == holiDays[i][1] - 1
          && date.getDate() == holiDays[i][2]) {
        return [true, 'holiday', holiDays[i][3]];
     }
   }
  return [true, ''];
    }

});
        var imgurl="{{user.e_img.url}}";
	$('#user_img').attr('src',imgurl);

    var fname="{{user.e_fname}}";
    {% if user.e_lname %}
    var lname="{{user.e_lname}}";
    var flname=fname+" "+lname
    {%else%}
    var flname=fname;
    {% endif %}
    $('#username').text(flname);

    $('#nof').val(0);

    $(".ldate").change(function() {
        var txt1 =  $.trim( $('#sdate').val());
        var txt2 =  $.trim( $('#edate').val());
            if (txt1 != "" && txt2 != "") {
               var s=txt1.split('/');
               var e=txt2.split('/');
               var f=new Date(txt1);
               var t=new Date(txt2);
               if(f<=t){
                   var diff=new Date(t-f);
               var days  = diff/1000/60/60/24;
               $('#nof').val(parseFloat(days+1));
               $("#chk_half").prop("checked", false);
               }
                else{

                   alert('Caution ! Invalid date range');
                   $("#chk_half").prop("checked", false);
                    $('#nof').val(0);
               }

            }

    });

    $("#chk_half").click(function(){
       if ($('#chk_half').is(":checked")) {
           if($('#nof').val()!=1 || ($('#txt1').val()!=$('#txt2').val())){
               alert('Half days must be applied seperately');
               $("#chk_half").prop("checked", false);

           }
           else if($('#nof').val()==1){

            $('#nof').val(0.5);
           }
       }
       else{
        $('#nof').val(1)
       }
    });

    $('#submit').click(function(){
        var f=0;
        if($('#nof').val()==0){
        alert('Please complete the details !');
        f=1;
        }
        if(f!=1){
            var cl=parseInt("{{user.e_cl}}");
            var sl=parseInt("{{user.e_sl}}");
            var el=parseInt("{{user.e_el}}");
            var fl=parseInt("{{user.e_fl}}");


            var lnof=parseInt($('#nof').val());
            var ltype=parseInt($('#leave_select').val());
            if(ltype==0&&((cl-lnof)<0)){
                alert('You dont have enough casual leaves to apply !');
                f=1;
            }else if(ltype==1&&((sl-lnof)<0)){
                alert('You dont have enough sick leaves to apply !');
                f=1;
            }else if(ltype==2&&((el-lnof)<0)){
                alert('You dont have enough earned leaves to apply !');
                f=1;
            }else if(ltype==3&&((fl-lnof)<0)){
                alert('You dont have enough flexi leaves to apply !');
                f=1;
            }

        }
        if(f==1){
            event.preventDefault();
        }
    });
});
</script>
{%endblock%}

Main Project/hrms/templates/ultimatix/attendance.html
{% extends 'ultimatix/admin/adminbase.html'%}

{%block body %}
<h2 class="w3ls_head">Upload Attendance</h2>
<div class="grid_3 grid_4 w3layouts">
    <div class="bs-example">
        <form action="{% url 'ultimatix:mark_attendance'%}" method="post" enctype="multipart/form-data">
            {% csrf_token%}
            {%if error%}
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="alert alert-danger" id="error">
                        <strong>Danger!</strong>{{error}}{{e}}
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
            {% elif success %}
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="alert alert-success" id="success">
                        <strong>Success!</strong>{{success}}
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
            {%endif%}
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <label for="adate">Date</label>
                    <input type="date" class="form-control" name="adate" id="adate">
                </div>
                <div class="col-md-4"></div>
            </div>
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <label for="myFile">Select a file: </label>
                    <input type="file" name="myFile" id="myFile" required>
                </div>
                <div class="col-md-4"></div>
            </div>
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button class="btn btn-primary form-control" name="validate" id="validate" value="validate">Validate & Submit</button>
                </div>
                <div class="col-md-4"></div>
            </div>
        </form>
    </div>
</div>
<script>
$(document).ready(function(){
	$('#attendance').addClass("active");
	$('#attendance_mark').addClass("active");

        var imgurl="{{user.e_img.url}}";
	$('#user_img').attr('src',imgurl);

	    var fname="{{user.e_fname}}";
    {% if user.e_lname %}
    var lname="{{user.e_lname}}";
    var flname=fname+" "+lname
    {%else%}
    var flname=fname;
    {% endif %}
    $('#username').text(flname);
});
</script>
{%endblock%}

Main Project/hrms/templates/ultimatix/payslip.html
{% extends 'ultimatix/admin/adminbase.html'%}

{%block body %}
<h2 class="w3ls_head">Salary Details</h2>
<div class="grid_3 grid_4 w3layouts ">
        <!--<h3 class="hdg">Headings</h3>-->
    <div class="bs-example">
        <form action="{% url 'ultimatix:generate_payslip'%}" method="post" enctype="multipart/form-data">
            {% csrf_token%}
            {%if error%}
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="alert alert-danger" id="error">
                        {{error}}{{e}}
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
            {% elif success %}
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="alert alert-success" id="success">
                        {{success}}
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
            {%endif%}
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <label for="sdate">Choose a Date</label>
                    <input type="date" class="form-control" name="sdate" id="sdate" required>
                </div>
                <div class="col-md-4"></div>
            </div>
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button class="btn btn-primary form-control" name="view" id="view" value="view" formtarget="">View Payslip</button>
                </div>
                <div class="col-md-4"></div>
            </div>
        </form>
    </div>
</div>


<script>
$(document).ready(function(){
	$('#pslip').addClass("active");
	$('#view_pslip').addClass("active");

        var imgurl="{{user.e_img.url}}";
	$('#user_img').attr('src',imgurl);

    var fname="{{user.e_fname}}";
    {% if user.e_lname %}
    var lname="{{user.e_lname}}";
    var flname=fname+" "+lname
    {%else%}
    var flname=fname;
    {% endif %}
    $('#username').text(flname);
});
</script>
{%endblock%}