Main Project/hrms/hrms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ultimatix.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main Project/hrms/ultimatix/urls.py
from django.urls import path
from . import views
app_name='ultimatix'

urlpatterns=[
path('home/',views.home_view,name='home_view'),
path('admin/designation/',views.designation_view,name='desig_mngt'),
path('admin/roles/',views.roles_view,name='roles_mngt'),
path('admin/regemp/',views.regemp_view,name='register_emp'),
path('admin/viewemp/',views.viewemp_view,name='view_emp'),
path('admin/viewemp/<int:pk>',views.updtemp_view,name='updt_emp'),
path('admin/createproject/',views.crtprj_view,name='create_project'),
path('admin/viewprojects/',views.proejcts_view,name='view_project'),
path('admin/viewprojects/<int:pid>',views.proejctmembers_view,name='project_members'),
path('admin/viewprojects/updt/<int:pid>',views.updtproj_view,name='updt_project'),
path('admin/allocate/',views.allocate_view,name='emp_allocate'),
#path('admin/deallocate/<int:pmid>',views.deallocate_view,name='emp_deallocate'),
path('ultimatix/attendance/',views.mark_attendance,name="mark_attendance"),
path('ultimatix/attendance/<str:adate>',views.upload_attendance,name="upload_attendance"),
path('ultimatix/applyleave/',views.apply_leave,name="apply_leave"),
path('ultimatix/leaverequest/',views.leave_request,name="leave_request"),
path('ultimatix/calendar/',views.calendar_view,name="calendar_view"),
path('ultimatix/payslip/',views.generate_payslip,name="generate_payslip"),
path('ultimatix/newsfeed/',views.news_feed,name='news_feed'),
path('ultimatix/admin/updttmsheet/',views.updttmsheet,name='updttmsheet'),
path('ultimatix/admin/dashboard/',views.admindashboard,name='admindashboard'),
path('ultimatix/salary/',views.salary_details,name="salary_details"),
path('ultimatix/adminappraisalreq',views.adminappraisalreq,name="adminappraisalreq"),

path('ultimatix/empview_projects',views.empview_projects,name="empview_projects"),
path('ultimatix/empview_projects/<int:pid>',views.empproejctmembers_view,name="empproject_members"),
path('ultimatix/empmyproject/',views.empmyproject,name="empmyproject"),
path('ultimatix/empdetails/',views.empdetails,name='empdetails'),
path('ultimatix/empleave/',views.empleave,name="empleave"),
path('ultimatix/empleavereq/',views.empleavereq,name="empleavereq"),
path('ultimatix/empcalendar/',views.empcalendar,name="empcalendar"),
path('ultimatix/emppayslip/',views.emppayslip,name="emppayslip"),
path('ultimatix/emptsupdt/',views.emptsupdt,name="emptsupdt"),
path('ultimatix/empdtlupdt/',views.empdtlupdt,name="empdtlupdt"),
path('ultimatix/empprofile/',views.empprofile,name="empprofile"),
path('ultimatix/empappraisal/',views.empappraisal,name="empappraisal"),
path('ultimatix/empappraisalreq/',views.empappraisalreq,name="empappraisalreq"),

path('',views.show_login,name="show_login"),


]

Main Project/hrms/ultimatix/views.py
import json
import os

import openpyxl
from django.db import connection,DatabaseError
from django.db.models import Max, Sum
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect

from ultimatix.utils import render_to_pdf
from .models import *
from datetime import datetime
import calendar
#import datetime
from ultimatix import config
import numpy as np
from django.db.models import Q
# Create your views here.
def dictfetchall(cursor):
    """Return all rows from a cursor as a dict"""
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def home_view(request):
    cursor = connection.cursor()
    try:
        logged_in = request.session['eid']
    except:
        logged_in = False

    if logged_in:
        date=datetime.now()
        #date=datetime.strptime('2020-01-01','%Y-%m-%d')
        if (date.day == calendar.monthrange(date.year, date.month)[1]):
            ob=Employee.objects.all().exclude(e_id='1022890')
            ed=str(calendar.monthrange(date.year, date.month)[1])
            yr=str(date.year)
            mn=str(date.month)
            if len(mn)==1:
                mn='0'+mn
            sdate=yr+"-"+mn+"-01"
            #print(sdate+" "+edate)
            sm=yr+"-"+mn
            #em=yr+"-"+str(date.month+1)
            yr2=str(date.year)
            #print('date.month'+str(date.month))
            if date.month==12:
                mn2='01'
                yr2=str(date.year+1)
            else:
                mn2=str(date.month+1)
                if len(mn2)==1:
                    mn2='0'+mn2
            em=yr2+"-"+mn2
            edate = yr + "-" + mn + "-" + ed
            print(sdate+" "+edate)
            print(sm + " "+em)

            busdays=np.busday_count(sm,em)
            print(busdays)

            for o in ob:
                #print(o.e_id)

                sql='''
                select count(*) from ultimatix_timesheet where eid_id=%s and tdate >=%s
                and tdate<=%s and tstate='P'
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                res=cursor.fetchone()
                p=int(res[0])

                sql='''
                select count(*) from ultimatix_timesheet where eid_id=%s and tdate >=%s
                and tdate<=%s and tstate='H'                
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                res=cursor.fetchone()
                h=0.5*int(res[0])

                sql='''
                select count(*) from ultimatix_timesheet where eid_id=%s and tdate >=%s
                and tdate<=%s and tstate='A'                
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                res=cursor.fetchone()
                a=int(res[0])

                sql='''
                select sum(nof) as sum from ultimatix_leave where eid_id=%s and sdate>=%s and edate<=%s
                and status='C'            
                '''
                cursor.execute(sql,[o.e_id,sdate,edate])
                #cursor.execute(sql)
                res=cursor.fetchone()
                #print(str(res))
                #print(int(res[0]))
                l=0
                if res[0]:
                    #print('record for : '+str(o.e_id))
                    l=int(res[0])
                #if str(o.e_id)=='1022892':
                tot=(p+h)+(a-l)
                print(str(p)+" "+str(h)+" "+str(a)+" "+str(l)+" "+str(tot))
                ctc= float(Employee_sal.objects.get(es_eid_id=o.e_id,es_status='Y').es_ctc)
                ctc_pm=float(ctc/12)
                ctc_pd=float(ctc_pm/int(calendar.monthrange(date.year, date.month)[1]))
                lop=0
                if tot<busdays:
                    lop=(float(busdays)-float(tot))*ctc_pd
                bs = ctc_pm * .40
                conv = ctc_pm * .18
                hra = ctc_pm * .12
                city = ctc_pm * .10
                sundry = ctc_pm * .06
                ptax = ctc_pm * .04
                pf = ctc_pm * .02
                esis = ctc_pm * .08
                r=Wage.objects.filter(eid_id=o.e_id,sdate=sdate,edate=edate,status='Y')
                if not r:
                    Wage.objects.create(eid_id=o.e_id,sdate=sdate,edate=edate,ctc=ctc,ctc_pm=round(ctc_pm,2),
                                        bs=round(float(bs),2),conv=round(float(conv),2),hra=round(float(hra),2),city=round(float(city),2),
                                        sundry=round(float(sundry),2),ptax=round(float(ptax),2),pf=round(float(pf),2),
                                        esis=round(float(esis),2),lop=round(float(lop),2),status='Y')
        elif date.day==1 and date.month in(1,4,7,10):
            ob = Employee.objects.all().exclude(e_id='1022890')
            if date.month == 1:
                for o in ob:
                    o.e_cl=2.0
                    o.e_sl=2.0
                    o.e_el=4.0
                    o.e_fl=2.0
                    o.save()
                    print('flexi and other leave credit')
            else:
                for o in ob:
                    r=Employee.objects.filter(e_id=str(o.e_id),e_cl=2.0,e_sl=2.0)
                    if not r:
                        o.e_cl=2.0
                        o.e_sl=2.0
                        o.e_el=float(o.e_el)+4.0
                        o.save()
                        print('credit other leave')
        else:
            print('not month end')
        news = News.objects.all().order_by('-nid')
        user = Employee.objects.get(e_id=logged_in)
        sql = '''
        select ud.d_role
        from ultimatix_employee ue
        left outer join ultimatix_employee_desig ued on ued.ed_eid_id = ue.e_id
        left outer join ultimatix_designation ud on ud.d_id = ued.ed_did_id
        where ued.ed_status = 'Y' and ue.e_id = %s
        '''
        cursor.execute(sql, [logged_in])
        res = cursor.fetchone()
        if str(res[0])=='0':
            role=0
        elif str(res[0])=='2':
            role=2
        elif str(res[0])=='1':
            role=1
        cursor.close()
        if role==0:
            return render(request, 'ultimatix/admin/adminhome.html',{'user':user,'news':news})
        else:
            return render(request,'ultimatix/employee/emphome.html',{'user':user,'news':news,'role':role})
    else:
        request.session['eid'] = None
        cursor.close()
        return redirect('ultimatix:show_login')





def designation_view(request):
    if request.is_ajax() and request.GET:
        try:
            cd = request.GET.get('cd')
            #print("code : "+cd)
            cursor = connection.cursor()
            sql = """
            select d_cd,d_desc,d_min,d_max,d_role from ultimatix_designation 
        	where d_cd=%s
            """
            cursor.execute(sql,[cd])
            #print("cursor : "+str(cursor))
            dict = dictfetchall(cursor)
            #print(str(dict))
            r = json.dumps(dict[0])
            cursor.close()
            return JsonResponse(r, safe=False)
        except DatabaseError  as e:
            print('Database error : ' + str(e))
        finally:
            if cursor:
                cursor.close()


    elif request.method=='POST':
        # return HttpResponse('submitted')
        cd = request.POST.get("cd")
        desc = request.POST.get("desc")

        if (request.POST.get("minexp").strip()) == '':
            min_exp = None
        else:
            min_exp = int(request.POST.get("minexp"))

        if (request.POST.get("maxexp").strip()) == '':
            max_exp = ''
        else:
            max_exp = int(request.POST.get("maxexp"))

        r_type = request.POST.get("role_select")
        # print('r_type : '+'*'+str(r_type)+'*')
        r_num = -1
        if r_type == "Employee":
            r_num = 1
        elif r_type == "HR":
            r_num = 2
        if request.POST.get("add"):
            ob=Designation.objects.filter(d_cd=cd)
            if ob:
                logged_in = request.session['eid']
                user = Employee.objects.get(e_id=logged_in)
                obj = Designation.objects.all().exclude(d_role=0)
                return render(request, 'ultimatix/admin/designation.html',
                             {'error': ' Designation already exists !','obj':obj,'user':user})
            else:
                try:
                    print('Entered for new save')
                    cursor = connection.cursor()
                    sql="""
                    insert into ultimatix_designation(d_cd,d_desc,d_min,d_max,d_role)
                    values(%s,%s,%s,%s,%s)
                    """
                    cursor.execute(sql, (cd, desc, min_exp, max_exp, r_num))
                    connection.commit()
                    cursor.close()
                    #obj=Designation.objects.create(d_cd=cd,d_desc=desc,d_min=min_exp,d_max=max_exp,d_role=r_num)
                    #obj.save()
                    logged_in = request.session['eid']
                    user = Employee.objects.get(e_id=logged_in)
                    obj = Designation.objects.all().exclude(d_role=0)
                    return render(request, 'ultimatix/admin/designation.html',
                              {'success': ' Data saved successfully!','obj':obj,'user':user})
                except DatabaseError  as e:
                    print('Database error : '+str(e))
                    connection.rollback()
                    obj = Designation.objects.all().exclude(d_role=0)
                    logged_in = request.session['eid']
                    user = Employee.objects.get(e_id=logged_in)
                    return render(request, 'ultimatix/admin/designation.html',
                              {'error': ' Database error.Please contact system admin!','obj':obj,'user':user})

Main Project/hrms/templates/ultimatix/admin/allocate.html
{% extends 'ultimatix/admin/adminbase.html'%}

{%block body %}
<h2 class="w3ls_head">Employee Allocation</h2>
<div class="grid_3 grid_4 w3layouts position-center">
<!--<h1>{{eid}}</h1>-->
    <div class="bs-example">
        <form action="{% url 'ultimatix:emp_allocate'%}" method="post" id="allocate_form" allocate-emp-url="{%url 'ultimatix:emp_allocate' %}">
            {% csrf_token%}
            {% if error %}
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="alert alert-danger" id="error">
                        <strong>Danger!</strong>{{error}}
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            {% elif success %}
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="alert alert-success" id="success">
                        <strong>Success!</strong>{{success}}
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            {%endif%}
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="project_select">Choose Project</label>
                </div>
                <div class="col-md-6">
                    <select  title="Choose Project" class="form-control" name="project_select" id="project_select" required>
                        {% for p in pobj%}
                        <option value="{{p.ptitle}}">{{p.pid}}</option>
                        {%endfor%}
                    </select>
                    <input type="hidden" value="" id="pid" name="pid">
                </div>

            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="pname">Name</label>
                </div>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="pname" id="pname" disabled>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="desig_select">Choose Designation</label>
                </div>
                <div class="col-md-6">

                    <select  title="Choose Designation" class="form-control" name="desig_select" id="desig_select" required>
                        <!--<option value="0">All</option>-->
                        {% for d in dobj%}
                        <option value="{{d.d_id}}">{{d.d_cd}}</option>
                        {%endfor%}
                    </select>

                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="emp_select">Employee</label>
                </div>
                <div class="col-md-6">
                    <select  title="Choose Employee" class="form-control" name="emp_select" id="emp_select" required>
                        {% for e in eobj%}
                        <option value="{{e.ename}}">{{e.eid}}</option>
                        {%endfor%}
                    </select>
                    <input type="hidden" value="" id="eid" name="eid">
                </div>

            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="empname">Employee Name</label>
                </div>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="empname" id="empname" disabled>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="role_select">Project Role</label>
                </div>
                <div class="col-md-6">
                    <select  title="Choose Employee" class="form-control" name="role_select" id="role_select" required>
                        {% for r in robj%}
                        <option value="{{r.r_id}}">{{r.r_cd}}</option>
                        {% endfor%}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="col-md-2"></div>
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary form-control" value="submit" name="submit" id="submit" >Allocate</button>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready(function(){
	$('#project').addClass("active");
	$('#emp_alloc').addClass("active");

    $('#pname').val(($("#project_select").val()));
    $('#pid').val($('#project_select').children("option:selected").text());

    $('#empname').val(($('#emp_select').children("option:selected").val()));
    $('#eid').val(($('#emp_select').children("option:selected").text()))

    $("#project_select").change(function(){
	    $('#pname').val(($("#project_select").val()));
	    $('#pid').val($(this).children("option:selected").text());
	});

    $("#emp_select").change(function(){
    $('#empname').val(($(this).children("option:selected").val()));
    $('#eid').val(($('#emp_select').children("option:selected").text()))
	});


    $("#desig_select").change(function(){
        var desig_cd=$("#desig_select option:selected").text();
        if(desig_cd=='HR' || desig_cd=='HR-M'){
            $('#role_select')[0].selectedIndex = 11;
        }else{
          $('#role_select')[0].selectedIndex = 0;
        }
	    var desid=$("#desig_select").val();
        var url = $("#allocate_form").attr("allocate-emp-url");
        $.ajax({
		    url: url,
		    method: 'GET',
		    data: {
			    desid: desid
			},
		    success: function(data){
            $("#emp_select").empty();
                for(i=0;i<data.length;i++){
                $("#emp_select").append(new Option(data[i].eid,data[i].ename));
                }
                $('#empname').val($("#emp_select option:first").val());
                $('#eid').val(($('#emp_select').children("option:selected").text()))
		    }
        });
	});

    var imgurl="{{user.e_img.url}}";
	$('#user_img').attr('src',imgurl);

    var fname="{{user.e_fname}}";
    {% if user.e_lname %}
    var lname="{{user.e_lname}}";
    var flname=fname+" "+lname
    {%else%}
    var flname=fname;
    {% endif %}
    $('#username').text(flname);

    $("#submit").click(function(){
        var f=0;
        desig_cd=$("#desig_select option:selected").text();
        role_cd=$("#role_select option:selected").text();
        if(desig_cd=='HR' || desig_cd=='HR-M') {

            if(role_cd!='MNG'){
                alert('Project role must be MNG for HR employees');
                f=1;
            }
        }

        if(f!=1){
            desig_cd=$("#desig_select option:selected").text();

            pname=$('#pname').val();
/*            alert(desig_cd);
            alert(pname);*/
            var t=0;
            var d=['SC','PC','VP','CEO','HR-M'];
            for(var i=0;i<d.length;i++){
                if(desig_cd==d[i]){
                    t=1;
                }
            }
            if(t==1 && pname!='TCS - MNG'){
                    alert('Choose TCS Management Project - 1006 (TCS - MNG) for single level employees');
                    f=1;
            }
            if(t==0 && pname=='TCS - MNG'){
                    alert('Choose TCS Management Project - 1006 (TCS - MNG) for single level employees');
                    f=1;
            }
        }
        if(f==1){
		event.preventDefault();
        }

    });

});
</script>
{%endblock%}

Main Project/hrms/templates/ultimatix/admin/deallocate.html
<h1>{{pmid}}</h1>

Main Project/hrms/templates/ultimatix/admin/updt_project.html
{% extends 'ultimatix/admin/adminbase.html'%}

{%block body %}
<h2 class="w3ls_head">Project Details</h2>
<div class="grid_3 grid_4 w3layouts position-center">
<!--<h1>{{eid}}</h1>-->
    <div class="bs-example">
        <form action="{% url 'ultimatix:updt_project' pobj.pid %}" method="post">
            {% csrf_token%}
            {% if error %}
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="alert alert-danger" id="error">
                        <strong>Danger!</strong>{{error}}
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            {% elif success %}
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="alert alert-success" id="success">
                        <strong>Success!</strong>{{success}}
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            {%endif%}
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="pid">Project Id</label>
                    <input type="text" class="form-control" name="pid" id="pid" value="{{pobj.pid}}" readonly>
                </div>
                <div class="col-md-6">
                    <label for="tle">Name</label>
                    <input type="text" class="form-control" name="tle" id="tle" value="{{pobj.ptitle}}" readonly>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="desc">Description</label>
                    <input type="text" class="form-control" name="desc" id="desc" value="{{pobj.pdesc}}"required>
                </div>
                <div class="col-md-6">
                    <label for="crtd">Created By</label>
                    <input type="text" class="form-control" name="crtd" id="crtd" value="{{pobj.pcrtd}}" readonly>
                </div>


            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="sdate">Start Date</label>
                    <input type="date" class="form-control" name="sdate" id="sdate" readonly>
                </div>
                <div class="col-md-6">
                    <label for="expedate">End Date (Expected)</label>
                    <input type="date" class="form-control" name="expedate" id="expedate">
                </div>

            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="client">Client</label>
                    <input type="text" class="form-control" name="client" id="client" value="{{pobj.pclient}}" required>
                </div>

                <div class="col-md-6">
                    <label for="status" >Proejct status</label>
                    <select  title="Choose Status" class="form-control" name="status" id="status" required>
                        <option value="A">Active</option>
                        <option value="C">Completed</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        {% if pobj.pedate %}
                        <a href="{%url 'ultimatix:view_project' %}" class="btn btn-primary">Back to details</a>
                        {%else%}
                        <button type="submit" class="btn btn-primary form-control" value="update" name="update" id="update" >Update Project</button>
                        {%endif%}

                    </div>
                    <div class="col-md-1"></div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready(function(){
	$('#project').addClass("active");
	$('#project_dtl').addClass("active");

	var s="{{pobj.psdate}}";
    date=new Date(s);
    y = date.getFullYear();
    m = date.getMonth()+1;
    d = date.getDate();
    if (d < 10) {
    d = '0' + d;
    }
    if (m < 10) {
    m = '0' + m;
    }
    document.getElementById('sdate').value = (y+'-' + m + '-'+d);



    {% if pobj.pexpedate %}
        var s1='{{pobj.pexpedate}}';
        date1=new Date(s1);
        y1 = date1.getFullYear();
        m1 = date1.getMonth()+1;
        d1 = date1.getDate();
        if (d1 < 10) {
        d1 = '0' + d1;
        }
        if (m1 < 10) {
        m1 = '0' + m1;
        }
        document.getElementById('expedate').value = (y1+'-' + m1 + '-'+d1);
        $("#expedate").prop('readonly', true);
    {% else %}
        $("#expedate").prop('readonly', false);
    {% endif %}

    var t1=new Date();
    var d1=t1.getDate();
    var m1=t1.getMonth()+1;
    var y1=t1.getFullYear();
    if(d1<10){
        d1='0'+d1
    }
    if(m1<10){
        m1='0'+m1
    }
    var mindate=y1+'-'+m1+'-'+d1;
    document.getElementById("expedate").setAttribute("min", mindate);


    var st="{{pobj.pstatus}}"
    if(st=='C'){
        $('#status')[0].selectedIndex = 1;
        $('#status').prop('disabled', true);
    }
    else if(st=='A'){
       $('#status')[0].selectedIndex = 0;
    }

    var imgurl="{{user.e_img.url}}";
	$('#user_img').attr('src',imgurl);

	    var fname="{{user.e_fname}}";
    {% if user.e_lname %}
    var lname="{{user.e_lname}}";
    var flname=fname+" "+lname
    {%else%}
    var flname=fname;
    {% endif %}
    $('#username').text(flname);
});
</script>
{%endblock%}

Main Project/hrms/templates/ultimatix/admin/viewprojects.html
{% extends 'ultimatix/admin/adminbase.html'%}

{%block body %}
<link rel="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>

<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
<link rel="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>-->
<h2 class="w3ls_head">Project Management</h2>
<div class="grid_3 grid_4 w3layouts">
<!--<h1>{{eid}}</h1>-->
    <div class="bs-example">
<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th style="color:black;">Project id</th>
                <th style="color:black;">Name</th>
                <th style="color:black;">Start Date</th>
                <th style="color:black;">Expected</th>
                <th style="color:black;">Budget</th>
                <th style="color:black;">Complexity</th>
                <th style="color:black;">Status</th>
<!--                <th style="color:black;">End Date</th>-->
                <th style="color:black;">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for p in pobj %}
            <tr>
                <td style="color:black;"><a href="{% url 'ultimatix:project_members' p.pid %}">{{p.pid}}</a></td>
                <td style="color:black;">{{p.ptitle}}</td>
                <td style="color:black;">{{p.psdate}}</td>
                <td style="color:black;">{{p.pexpedate}}</td>
                <td style="color:black;">{{p.pbudget}}</td>
                <td style="color:black;">{{p.pcomplexity}}</td>
                <td style="color:black;">{{p.pstatus}}</td>
<!--                <td style="color:black;">
                    {% if p.pedate %}
                        {{p.pedate}}
                    {% else %}
                            -
                    {%endif%}
                </td>-->
                <td>
                    <a href="{%url 'ultimatix:updt_project' p.pid %}" class="btn btn-primary form-control">Update</a>
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

    </div>
</div>

<script>
$(document).ready(function(){
	$('#project').addClass("active");
	$('#project_dtl').addClass("active");
	$('#example').DataTable();


        var imgurl="{{user.e_img.url}}";
	$('#user_img').attr('src',imgurl);

	var fname="{{user.e_fname}}";
    {% if user.e_lname %}
    var lname="{{user.e_lname}}";
    var flname=fname+" "+lname
    {%else%}
    var flname=fname;
    {% endif %}
    $('#username').text(flname);
});
</script>
{%endblock%}